export const ADD_PLACE = 'ADD_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';

export const SET_PLACES = 'SET_PLACES';
export const PLACE_ADDED = 'PLACE_ADDED';
export const START_ADD_PLACE = 'START_ADD_PLACE';
export const PLACE_DELETED = 'PLACE_DELETED';
export const START_DELETE_PLACE = 'START_PLACE_DELETE';

export const PUT_AUTH = 'PUT_AUTH';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
